auth:
    enable: false
    username: admin
    pattern:
        - "/game/*/*"
    password: "123123123"

serverAuth:
    enable: true
    match:
      biz:
        header: "server-auth"
        pattern:
          - "/biz/*/*"
        keys:
          - "abc"